#### GENERAL ####

# this is the desired analysis sampleRate, not that of the file
# if the file has a different sampleRate, it will be resampled
# to have the same sampleRate as specified here.
analysisSampleRate: 44100

# compute the audio file from start time to end time (in seconds)
startTime: 0.0
endTime: 20.0

# whether to apply equal loudness contour (filter): yes|no|both
equalLoudness: false #true
nequalLoudness: false #true
shortSound: false # set to true when analyzing a sample less than 2s

# change to true when svm models are trained
svm:
    compute: true

highlevel:
    compute: true
    svm_models: ['src/musicAnalysis/svm_models/genre_tzanetakis.history',
                'src/musicAnalysis/svm_models/danceability.history',
                'src/musicAnalysis/svm_models/tonal_atonal.history',
                'src/musicAnalysis/svm_models/mood_sad.history',
                'src/musicAnalysis/svm_models/genre_electronic.history',
                'src/musicAnalysis/svm_models/mood_acoustic.history',
                'src/musicAnalysis/svm_models/mood_aggressive.history',
                'src/musicAnalysis/svm_models/mood_electronic.history',
                'src/musicAnalysis/svm_models/mood_happy.history', 
                'src/musicAnalysis/svm_models/mood_party.history', 
                'src/musicAnalysis/svm_models/mood_relaxed.history',
                'src/musicAnalysis/svm_models/timbre.history',  
                'src/musicAnalysis/svm_models/voice_instrumental.history', 
                'src/musicAnalysis/svm_models/genre_rosamerica.history']
segmentation:
    compute: false
    cpw: 5
    size1: 1000
    inc1: 300
    size2: 600
    inc2: 50
    minimumSegmentsLength: 10.0 # seconds

lowlevel:
    compute: false #true
    frameSize: 2048
    hopSize:   1024
    zeroPadding:  0
    silentFrames: 'noise'
    windowType:  'blackmanharris62'
    stats: [ "mean", "var", "min","median", "max", "dmean", "dmean2", "dvar", "dvar2" ]
    mfccStats: [ "mean", "cov", "icov" ]

# average loudness options (average_loudness)
average_loudness:
    compute: false #true
    frameSize: 88200
    hopSize:   44100


rhythm:
    compute: false #true
    # whether or not to use onsets as periodicity function
    useOnset: true
    # whether or not to use energy bands as periodicity function
    useBands: true

    # sizes of frames. Note that frameNumber*hopSize ~= about 6 seconds
    numberFrames: 1024
    hopSize:      256
    frameSize:   1024
    frameHop:    1024
    stats: [ "mean", "var", "min","median", "max", "dmean", "dmean2", "dvar", "dvar2" ]

# tonal extractor options (chords_changes_rate, chords_number_rate,
#                          chords_strength, key_strength,
#                          tuning_frequency, hpcp, chords_key,
#                          tuning_diatonic_strength,
#                          tuning_equal_tempered_deviation,
#                          tuning_nontempered_energy_ratio,
#                          chords_scale, key_key, key_scale)
tonal:
    compute: false #true
    frameSize:   4096
    hopSize:     2048
    zeroPadding:    0
    silentFrames: 'noise'
    windowType:  'blackmanharris62'
    stats: [ "mean", "var", "min","median", "max", "dmean", "dmean2", "dvar", "dvar2" ]

sfx: # pitch_max_to_total, pitch_min_to_total, pitch_centroid,
     # pitch_after_max_before_max_energy_ratio,
    compute: false #true
    stats: [ "mean", "var", "min","median", "max", "dmean", "dmean2", "dvar", "dvar2" ]

# sfx not available at the moment...
# (temporal_decrease, temporal_kurtosis, temporal_skewness
#  temporal_spread, temporal_centroid, effective_duration,
#  logattacktime, strong_decay, flatness,
#  max_to_total, tc_to_total,
#  der_av_after_max, max_der_befor_max)

panning:
    compute: false
    frameSize: 8192
    hopSize: 2048
    zeropadding: 8192
    silentFrames: 'noise'
    windowType: 'hann'
    stats: [ 'copy' ]
